// =======================================================================
// SET : Welcome to Night City (abréviation : WNC) — Cyberpunk TCG, 1er set
// Pour ajouter un futur set : crée sets/<abbr>.js sur ce même modèle
// (const <ABBR>_CARDS = [...]) puis inclus-le dans index.html + ajoute-le
// à la liste CARDS plus bas dans le script principal.
// =======================================================================
const WNC_CARDS = [
{n:"6th Street Recruits",t:"Unit",f:["6th Street","Ganger"],c:4,p:6,r:1,text:"When a friendly Unit steals a d6, increase a Gig by up to 6."},
{n:"Adam Smasher — Ender of Legends",t:"Legend",f:["Arasaka","Merc"],c:9,p:9,r:2,text:"{Go Solo} (Pay this Legend's cost to play it as a ready Unit. It can attack this turn. If it leaves the field, remove it from the game.) {Play} Defeat a rival Unit."},
{n:"Adam Smasher — Metal Over Meat",t:"Unit",f:["Arasaka","Merc"],c:9,p:15,r:6,text:"{Play} Defeat all other Units."},
{n:"Afterparty at Lizzie's",t:"Program",f:["Braindance","Mox"],c:1,p:null,r:1,text:"Adjust a Gig by up to 1. If you control 2 or more Gigs with different values, draw 1."},
{n:"All is Lost",t:"Program",f:["Zetatech"],c:1,p:null,r:2,text:"Trash 3. Add a Unit from among them to your hand."},
{n:"Alt Cunningham — Mother of Daemons",t:"Unit",f:["Merc","Netrunner"],c:7,p:8,r:3,text:"When a friendly equipped Unit or Legend is spent, draw 1. When a rival Unit would steal a Gig, you may discard 1 with cost equal to that Gig's value. If you do, the Gig isn't stolen."},
{n:"Alt Cunningham — Soulkiller Architect",t:"Legend",f:["Merc","Netrunner"],c:null,p:null,r:2,text:"{Spend} Your next Program this turn plays for -1 €$ for each friendly min Gig, to a minimum of 1 €$. 1 €$, {Spend} Play a Program from your trash. Bottom-deck it after you play it. (You still pay its cost.)"},
{n:"Armored Minotaur",t:"Unit",f:["Arasaka","Militech","Drone"],c:6,p:9,r:4,text:"PLAY If you have 12+ (Street Cred), defeat a rival unit with power 5 or less."},
{n:"Augmented Negotiators",t:"Unit",f:["Arasaka","Corpo"],c:3,p:2,r:1,text:"{Blocker} (You may spend this Unit to redirect a rival Unit's attack to it instead.) When this Unit uses {Blocker}, a Rival discards 1."},
{n:"Appetite for Destruction",t:"Program",f:["Ganger"],c:3,p:null,r:4,text:"The next time a friendly Unit wins a fight by 3+ power this turn, it also steals a Gig."},
{n:"Bonnie and Clyde",t:"Program",f:["Braindance"],c:3,p:null,r:3,text:"Defeat a rival Unit with power 4 or less. You may defeat 2 instead if a Rival controls at least 2 Gigs more than you."},
{n:"Bootleg Black Sapphire Show",t:"Program",f:["Braindance"],c:5,p:null,r:4,text:"Sell the top card of your deck. If you control a Gig with an even value and a Gig with an odd value, draw 2."},
{n:"Caliber — Totentanz's Top Dog",t:"Unit",f:["Ganger","Maelstrom"],c:5,p:5,r:2,text:"{Play} Defeat a rival Unit with cost 2 or less. {Defeated} A Rival discards 1. If the card's cost equals the value of a friendly Gig, that Rival discards 1 more."},
{n:"Carnage at the Colosseum",t:"Program",f:["Braindance","Extreme"],c:6,p:null,r:3,text:"Play this Program for -1 €$ for each friendly Gig with 8+ value, to a minimum of 1 €$. Defeat a rival Unit with less power than a friendly Unit."},
{n:"Chrome Reverie",t:"Program",f:["Braindance"],c:3,p:null,r:1,text:"A rival Unit can't attack until your next turn. If you control a min Gig, you may Call a Legend for free. (You can only Call a Legend once per turn.)"},
{n:"Corpo Security",t:"Unit",f:["Corpo"],c:2,p:2,r:1,text:"This Unit can't attack. {Blocker} (You may spend this Unit to redirect a rival Unit's attack to it instead.)"},
{n:"Corporate Surveillance",t:"Program",f:["Corpo"],c:2,p:null,r:1,text:"Spend a rival Unit with cost 4 or less."},
{n:"Cyberpsychosis",t:"Program",f:["Quickhack"],c:3,p:null,r:2,text:"{Quick} Give an equipped Unit +3 power this turn for each if its equipped Gears. If that Unit steals or fights, defeat it at the end of this turn."},
{n:"Delamain Cab",t:"Unit",f:["Vehicle"],c:4,p:7,r:3,text:""},
{n:"Dexter DeShawn — One Last Chance",t:"Unit",f:["Fixer"],c:3,p:4,r:2,text:"{Play} {Attack} Adjust a Gig by up to 1. {Defeated} If your Street Cred differs from a Rival's by 10+, draw 2."},
{n:"Dum Dum — Maelstrom Triggerman",t:"Legend",f:["Ganger","Maelstrom"],c:null,p:null,r:2,text:"{Call} You may defeat a friendly Gear. If you do, draw 2. Otherwise, draw 1. {Quick} 1 €$, {Spend} Give a friendly Unit +1 power this turn for each of its equipped Gear."},
{n:"Dying Night — V's Pistol",t:"Gear",f:["Merc","Weapon"],c:2,p:2,r:2,text:"(Equip to a friendly Unit or face-up Legend.) {Attack} Decrease a Gig by up to 2. At the end of your turn, if this Unit is named \"V\", ready 2 Eddies."},
{n:"El Sombrerón — La Venganza Lenta",t:"Unit",f:["Ganger","Valentino"],c:5,p:4,r:4,text:"{Attack} You may pay 2 €$. If you do, this Unit gains power equal to a friendly max Gig this turn."},
{n:"Emergency Atlus",t:"Unit",f:["Trauma Team","Vehicle","Zetatech"],c:3,p:4,r:1,text:"\"Grab the policyholder, leave the rest for the city meatwagon.\""},
{n:"Evelyn Parker — Beautiful Enigma",t:"Legend",f:["Doll"],c:null,p:null,r:2,text:"When a friendly CORPO or GANGER Unit steals 1 or more Gigs, ready 1 Eddie. 1 €$, {Spend} A rival Unit must attack next turn if it can."},
{n:"Evelyn Parker — Scheming Siren",t:"Unit",f:["Doll"],c:2,p:0,r:3,text:"{Attack} Draw 1. Then, if you have more Street Cred than a Rival, discard 1. (Units with power 0 don't steal Gigs.)"},
{n:"Field Operator",t:"Unit",f:["Arasaka","Corpo","Techie"],c:3,p:2,r:2,text:"{Play} If your Street Cred is an even number, draw 1."},
{n:"Floor It",t:"Program",f:["Merc","Quickhack"],c:1,p:null,r:2,text:"{Quick} Give a rival Unit -1 power this turn. Draw 1."},
{n:"Gilded Matón",t:"Unit",f:["Ganger","Valentino"],c:4,p:3,r:2,text:"{Play} You may defeat a friendly Gear. If you do, defeat a rival Unit with cost 3 or less."},
{n:"Gorilla Arms",t:"Gear",f:["Cyberware"],c:4,p:3,r:3,text:"(Equip to a friendly Unit or face-up Legend.) The first time this Unit steals 1 or more Gigs each turn, steal a rival Gig with a value not shared by a friendly Gig."},
{n:"Goro Takemura — Hands Unclean",t:"Legend",f:["Arasaka","Corpo"],c:5,p:7,r:2,text:"{Go Solo} (Pay this Legend's cost to play it as a ready Unit. It can attack this turn. If it leaves the field, remove it from the game.) {Blocker} (You may spend this Unit to redirect a rival Unit's attack to it instead.)"},
{n:"Goro Takemura — Losing His Way",t:"Unit",f:["Arasaka","Corpo"],c:4,p:4,r:3,text:"{Attack} If all friendly Legends are face-up, this Unit has +5 power this turn."},
{n:"Goro Takemura — Vengeful Bodyguard",t:"Legend",f:["Arasaka","Corpo"],c:null,p:null,r:2,text:"{Quick} 1 €$, {Spend} Give a friendly Unit with cost 4 or less {Blocker} this turn. If you control a value-pair of Gigs, also give it +1 power this turn. When a friendly Unit uses {Blocker}, you may discard 1. If you do, draw 1."},
{n:"Hanako Arasaka — Daughter of the Emperor",t:"Legend",f:["Arasaka","Corpo","Netrunner"],c:null,p:null,r:2,text:"{Spend} Swap a friendly Gig with a rival Gig. At the start of your turn, draw 1 for each friendly value-pair of Gigs."},
{n:"Hanako Arasaka — In a Gilded Cage",t:"Unit",f:["Arasaka","Corpo","Netrunner"],c:4,p:1,r:2,text:"{Play} Search the top 4 cards of your deck. Reveal any number of cards with cost equal to any friendly Gig values and add them to your hand. Bottom-deck the rest."},
{n:"Industrial Assembly",t:"Program",f:["Arasaka","Braindance"],c:1,p:null,r:1,text:"Increase a Gig by up to 4. If you control a Gig with 8+ value, draw 1."},
{n:"Jackie Welles — Mama's Favorite",t:"Legend",f:["Merc"],c:6,p:8,r:2,text:"{Go Solo} (Pay this Legend's cost to play it as a ready Unit. It can attack this turn. If it leaves the field, remove it from the game.) If a friendly Unit would be defeated, you may spend 1 €$ to defeat this Legend instead. (Remove it from the game.)"},
{n:"Jackie Welles — Pour One Out For Me",t:"Legend",f:["Merc"],c:null,p:null,r:2,text:"The first time you play a Blue Unit or Blue Gear each turn, you may decrease a friendly Gig by up to 2. If it becomes a min Gig, draw 1."},
{n:"Jackie Welles — Ride or Die Choom",t:"Unit",f:["Merc","Valentino"],c:6,p:8,r:2,text:"{Attack} Give this Unit +2 power this turn for each friendly Gig with an even value. {Defeated} Draw 1 for each friendly Gig with an odd value."},
{n:"Japantown Jonin",t:"Unit",f:["Tyger Claws"],c:2,p:0,r:2,text:"{Play} Give a friendly Unit +2 power this turn. (Units with power 0 don't steal Gigs.)"},
{n:"Johnny Silverhand — Rocking Renegade",t:"Legend",f:["Merc","Rocker","Samurai"],c:null,p:null,r:2,text:"2 €$, {Spend} A friendly Unit can attack spent rival Units the turn it's played. If it's a ROCKER Unit, also give it +2 power this turn. This effect costs -1 €$ for each friendly Gig with 8+ value."},
{n:"Kerry Eurodyne — Axe, Attitude, Audience",t:"Legend",f:["Rocker","Samurai"],c:null,p:null,r:2,text:"When you roll in a Gig from your fixer area, you may ignore the result and reroll it once. When you roll a min or max value on a Gig, draw 1. If it's a d20, draw 3 instead."},
{n:"Kerry Eurodyne — The Last Rockerboy",t:"Unit",f:["Rocker","Samurai"],c:4,p:5,r:1,text:"{Spend} If you control a Gig with 8+ value, draw 2."},
{n:"Kiroshi Optics",t:"Gear",f:["Cyberware"],c:1,p:1,r:1,text:"(Equip to a friendly Unit or face-up Legend.) {Attack} Look at a friendly face-down Legend. (Don't reveal it.)"},
{n:"La Llorona — Ghost of the Past",t:"Unit",f:["Ganger","Valentino"],c:3,p:3,r:1,text:"{Blocker} (You may spend this Unit to redirect a rival Unit's attack to it instead.) When this Unit uses {Blocker}, increase a Gig by up to 3."},
{n:"Live with the Aftermath",t:"Program",f:["Plan"],c:3,p:null,r:3,text:"Each player defeats one of their Units."},
{n:"Lizzy Wizzy — Delicate Weapon",t:"Unit",f:["Rocker"],c:5,p:2,r:2,text:"{Play} You may play a Program with cost 3 or less from your hand or trash for free. Bottom-deck it after you play it. {Blocker}"},
{n:"Maman Brigitte — Spirit of Death",t:"Unit",f:["Mystic","Netrunner","Voodoo Boys"],c:5,p:3,r:4,text:"{Play} You may discard 2 Programs. If you do, bottom-deck a rival unequipped Unit."},
{n:"Mandibular Upgrade",t:"Gear",f:["Cyberware"],c:1,p:0,r:2,text:"(Equip to a friendly Unit or face-up Legend.) {Blocker} (You may spend this Unit to redirect a rival Unit's attack to it instead.)"},
{n:"Mantis Blades",t:"Gear",f:["Cyberware"],c:1,p:2,r:1,text:"(Equip to a friendly Unit or face-up Legend.) \"One cut, one kill.\""},
{n:"MaxTac Suppression Team",t:"Unit",f:["NCPD"],c:5,p:7,r:1,text:"Rival Units can't attack the turn they're played."},
{n:"Meredith Stout — Stone Cold Corpo",t:"Unit",f:["Corpo","Militech"],c:4,p:5,r:1,text:"{Blocker} This Unit has +2 power while fighting a Legend. When a Rival adjusts or swaps 1 or more friendly Gigs, you may add a card from your trash to your hand."},
{n:"Minotaur",t:"Unit",f:["Arasaka","Drone","Militech"],c:7,p:9,r:2,text:"{Play} If you have more Street Cred than a Rival, defeat a rival Unit with power 5 or less."},
{n:"Misty Olszewski — Mender of Broken Spirits",t:"Unit",f:["Mystic"],c:3,p:0,r:2,text:"This Unit can't attack. At the end of your turn, choose a card type. Then, reveal the top card of your deck. If it's the chosen type, add it to your hand and ready 1 Eddie. Otherwise, trash it. (Card types include Unit, Gear, and Program.)"},
{n:"Modded Kusanagi",t:"Unit",f:["Tyger Claws","Vehicle"],c:6,p:8,r:2,text:"{Adrenaline} (This Unit can attack the turn it's played.) At the end of your turn, return this Unit to its owner's hand."},
{n:"Mox Inciters",t:"Unit",f:["Ganger","Mox"],c:3,p:2,r:2,text:"{Play} A rival Unit must attack next turn if it can. {Blocker} (You may spend this Unit to redirect a rival Unit's attack to it instead.)"},
{n:"MT0D12 Flathead",t:"Unit",f:["Drone","Militech"],c:5,p:7,r:3,text:"If you have less Street Cred than a Rival, this Unit can't be blocked."},
{n:"Nadia — Fighting Through Grief",t:"Unit",f:["Medtech","Trauma Team"],c:6,p:8,r:2,text:"If a Rival controls more Gigs than you, this Unit can attack their Gig area the turn it's played."},
{n:"Octant",t:"Unit",f:["Drone","Militech","Zetatech"],c:7,p:8,r:4,text:"Play this Unit for -1 €$ for each friendly Gig with 8+ value, to a minimum of 1 €$."},
{n:"Offduty Malfini",t:"Unit",f:["Ganger","Voodoo Boys"],c:4,p:5,r:2,text:"{Play} Spend this Unit and a rival Unit."},
{n:"Over the Edge",t:"Program",f:["Merc"],c:3,p:null,r:2,text:"Defeat a Unit with power equal to or less than the value of a friendly d20."},
{n:"Overwatch — Panam's Gift",t:"Gear",f:["Weapon"],c:4,p:4,r:4,text:"{Quick} 1 €$, {Spend} Discard 1. Defeat a spent rival Unit with cost equal to or less than the discarded card's cost."},
{n:"Panam Palmer — Nomad Cavalry",t:"Legend",f:["Aldecado","Merc","Nomad"],c:null,p:null,r:2,text:"2 €$, {Spend} Move a Gear from this Legend to an unequipped friendly Unit. If you do, ready that Unit. At the end of your turn, if 5 or more friendly Units and/or Legends are equipped, ready them."},
{n:"Peace Offering",t:"Program",f:["Braindance"],c:1,p:null,r:1,text:"You may set a Gig's value to the value of another Gig. Then, if you control a value-pair, draw 1."},
{n:"Pepe Najarro — Working Doubles",t:"Unit",f:["Valentino"],c:4,p:6,r:2,text:"{Attack} If you control a value-pair of Gigs, ready up to 2 MERC Legends in your Legends area."},
{n:"Placide — Voodoo Sentinel",t:"Unit",f:["Ganger","Netrunner","Voodoo Boys"],c:8,p:10,r:2,text:"{Play} {Attack} You may discard 1 Program. If you do, bottom-deck a rival Unit."},
{n:"Psycho Squad",t:"Unit",f:["NCPD"],c:4,p:6,r:1,text:"Their protocol stops at \"shoot first.\""},
{n:"Reboot Optics",t:"Program",f:["Tech"],c:2,p:null,r:2,text:"Give a friendly unit +4 power this turn. Defeat it at the end of the turn. (Discard programs after they resolve.)"},
{n:"Riding Nomad",t:"Unit",f:["Nomad"],c:5,p:4,r:4,text:"{Adrenaline} (This Unit can attack the turn it's played.)"},
{n:"River Ward — Detective on the Hunt",t:"Legend",f:["NCPD"],c:null,p:null,r:2,text:"{Quick} {Spend} Play a Gear with cost 2 or less from your hand for free. When a friendly equipped Unit is defeated, search the top 2 cards of your deck and trash 1."},
{n:"Royce — Don't Call Me Simon",t:"Unit",f:["Ganger","Maelstrom"],c:5,p:4,r:2,text:"{Play} Defeat a rival Unit with power 2 or less. If you have more Street Cred than a Rival, defeat a rival Unit with power 3 or less instead."},
{n:"Royce — Psycho on the Edge",t:"Legend",f:["Ganger","Maelstrom"],c:6,p:6,r:2,text:"{Go Solo} (Pay this Legend's cost to play it as a ready Unit. It can attack this turn. If it leaves the field, remove it from the game.) During your turn, this Legend has +2 power for each of its equipped Gear."},
{n:"Ruthless Lowlife",t:"Unit",f:["Arasaka","Merc"],c:2,p:1,r:1,text:"When a rival steals one or more friendly gigs, if this unit is spent, the value of those gigs becomes 1."},
{n:"Saburo Arasaka — Stubborn Patriarch",t:"Legend",f:["Arasaka","Corpo"],c:null,p:0,r:2,text:"Friendly ARASAKA Units have +1 power while attacking. (Units steal an extra Gig for every 10 power.)"},
{n:"Sandayu Oda — Hanako's Guardian",t:"Unit",f:["Arasaka","Corpo"],c:7,p:8,r:2,text:"{Play} Spend a rival Unit for each friendly value-pair of Gigs. This Unit can attack rival Units the turn it's played."},
{n:"Sandevistan",t:"Gear",f:["Cyberware"],c:3,p:2,r:3,text:"(Equip to a friendly Unit or face-up Legend.) At the end of your turn, ready this Unit or Legend."},
{n:"Satori — Sword of Saburo",t:"Gear",f:["Arasaka","Weapon"],c:2,p:2,r:1,text:"(Equip to a friendly Unit or face-up Legend.) When this Unit wins a fight against a rival Unit, draw 1."},
{n:"Saul Bright — Stormrider",t:"Unit",f:["Aldecado","Nomad"],c:8,p:14,r:2,text:"Other friendly Units have +2 power while attacking. At the end of your turn, ready up to 3 friendly Units."},
{n:"Screw — Lovelorn Fool",t:"Unit",f:["Ganger","Maelstrom"],c:5,p:7,r:2,text:"{Defeated} Add another Unit from your trash to your hand."},
{n:"Secondhand Bombus",t:"Unit",f:["Drone","Zetatech"],c:2,p:0,r:2,text:"{Blocker} (You may spend this Unit to redirect a rival Unit's attack to it instead.) (Units with power 0 don't steal Gigs.)"},
{n:"Sketchy Ripper",t:"Unit",f:["Ganger","Ripperdoc","Scavenger"],c:2,p:0,r:2,text:"{Attack} Search the top 3 cards of your deck. Reveal a Gear and add it to your hand. Bottom-deck the rest. (Units with power 0 don't steal Gigs.)"},
{n:"Swordwise Huscle",t:"Unit",f:["Merc"],c:3,p:3,r:2,text:"{Attack} If this Unit has power 5+, draw 1."},
{n:"T-Bug — Amateur Philosopher",t:"Unit",f:["Merc","Netrunner"],c:4,p:4,r:2,text:"{Defeated} Look at all friendly face-down Legends. Then, you may Call a Legend for free. (You can only Call a Legend once per turn.)"},
{n:"Take Control",t:"Program",f:["Quickhack"],c:2,p:null,r:2,text:"{Quick} A rival Unit steals 1 fewer Gig this turn. If that Unit is an AI, DRONE, or VEHICLE, draw 1."},
{n:"The Heist",t:"Program",f:["Merc"],c:2,p:null,r:2,text:"Trash 4. Add a Gear from among them to your hand. If that Gear's cost equals the value of a friendly Gig, you may play it for free instead."},
{n:"The Relic — Experimental Biochip",t:"Gear",f:["Arasaka","Cyberware"],c:5,p:3,r:4,text:"{Defeated} Play another Unit with cost 9 or less from your trash for free. Then, bottom-deck this Unit."},
{n:"V — StreetKid",t:"Legend",f:["Merc"],c:5,p:6,r:2,text:"{Call} Trash 3. Then, add 1 BRAINDANCE Program from your trash to your hand. {Go Solo} (Pay this Legend's cost to play it as a ready Unit. It can attack this turn. If it leaves the field, remove it from the game.)"},
{n:"Valentino Guerrera",t:"Unit",f:["Ganger","Valentino"],c:3,p:4,r:2,text:"If you have more Street Cred than a Rival, this Unit can attack ready Units with {Blocker}."},
{n:"Valentino Street Racer",t:"Unit",f:["Valentino","Vehicle"],c:3,p:3,r:2,text:"{Play} Give another friendly Unit with cost 5 or less {Adrenaline} this turn. (A Unit with Adrenaline can attack the turn it's played.)"},
{n:"Viktor Vektor — Sit Down and Relax",t:"Legend",f:["Ripperdoc"],c:null,p:null,r:2,text:"{Call} Search the top 5 cards of your deck. Reveal up to 2 Gears with cost 2 or less and add them to your hand. Bottom-deck the rest in a random order."},
{n:"Viktor Vektor — You Might Feel a Little Pinch",t:"Unit",f:["Ripperdoc"],c:3,p:3,r:2,text:"{Play} Play a CYBERWARE Gear with cost 2 or less from your trash for free. Equip it only to another friendly Unit."},
{n:"Wraith Marauders",t:"Unit",f:["Ganger","Nomad","Raffen Shiv"],c:5,p:4,r:2,text:"When this Unit steals a Gig, ready another friendly Unit with power equal to the Gig's value."},
{n:"Yorinobu Arasaka — Embracing Destruction",t:"Legend",f:["Arasaka","Corpo"],c:null,p:null,r:2,text:"The first time a friendly ARASAKA Unit attacks each turn, draw 1. Then, if you have less than 20 Street Cred, discard 1."},
{n:"Yorinobu Arasaka — Steel Dragon",t:"Unit",f:["Arasaka","Corpo"],c:7,p:9,r:3,text:"{Play} You may play a Unit with cost 4 or less from your hand or trash for free. It can attack rival Units this turn. The first time an ARASAKA Unit is defeated each turn, draw 1."},
{n:"Zetatech Faceplate",t:"Gear",f:["Cyberware","Zetatech"],c:2,p:2,r:2,text:"(Equip to a friendly Unit or face-up Legend.) When this Unit or Legend is spent, adjust a Gig by up to 1. Then, if you control 3 or more Gigs with different values, draw 1."},
];
