// =======================================================================
// SET : Welcome to Night City (abréviation : WNC) — Cyberpunk TCG, 1er set
// Pour ajouter un futur set : crée sets/<abbr>.js sur ce même modèle
// (const <ABBR>_CARDS = [...]) puis inclus-le dans index.html + ajoute-le
// à la liste CARDS plus bas dans le script principal.
// =======================================================================
const WNC_CARDS = [
{n:"6th Street Recruits",t:"Unit",f:["6th Street","Ganger"],c:4,p:6,r:1},
{n:"Adam Smasher — Ender of Legends",t:"Legend",f:["Arasaka","Merc"],c:9,p:9,r:2},
{n:"Adam Smasher — Metal Over Meat",t:"Unit",f:["Arasaka","Merc"],c:9,p:15,r:6},
{n:"Afterparty at Lizzie's",t:"Program",f:["Braindance","Mox"],c:1,p:null,r:1},
{n:"All is Lost",t:"Program",f:["Zetatech"],c:1,p:null,r:2},
{n:"Alt Cunningham — Mother of Daemons",t:"Unit",f:["Merc","Netrunner"],c:7,p:8,r:3},
{n:"Alt Cunningham — Soulkiller Architect",t:"Legend",f:["Merc","Netrunner"],c:null,p:null,r:2},
{n:"Armored Minotaur",t:"Unit",f:["Arasaka","Militech","Drone"],c:6,p:9,r:4},
{n:"Augmented Negotiators",t:"Unit",f:["Arasaka","Corpo"],c:3,p:2,r:1},
{n:"Appetite for Destruction",t:"Program",f:["Ganger"],c:3,p:null,r:4},
{n:"Bonnie and Clyde",t:"Program",f:["Braindance"],c:3,p:null,r:3},
{n:"Bootleg Black Sapphire Show",t:"Program",f:["Braindance"],c:5,p:null,r:4},
{n:"Caliber — Totentanz's Top Dog",t:"Unit",f:["Ganger","Maelstrom"],c:5,p:5,r:2},
{n:"Carnage at the Colosseum",t:"Program",f:["Braindance","Extreme"],c:6,p:null,r:3},
{n:"Chrome Reverie",t:"Program",f:["Braindance"],c:3,p:null,r:1},
{n:"Corpo Security",t:"Unit",f:["Corpo"],c:2,p:2,r:1},
{n:"Corporate Surveillance",t:"Program",f:["Corpo"],c:2,p:null,r:1},
{n:"Cyberpsychosis",t:"Program",f:["Quickhack"],c:3,p:null,r:2},
{n:"Delamain Cab",t:"Unit",f:["Vehicle"],c:4,p:7,r:3},
{n:"Dexter DeShawn — One Last Chance",t:"Unit",f:["Fixer"],c:3,p:4,r:2},
{n:"Dum Dum — Maelstrom Triggerman",t:"Legend",f:["Ganger","Maelstrom"],c:null,p:null,r:2},
{n:"Dying Night — V's Pistol",t:"Gear",f:["Merc","Weapon"],c:2,p:2,r:2},
{n:"El Sombrerón — La Venganza Lenta",t:"Unit",f:["Ganger","Valentino"],c:5,p:4,r:4},
{n:"Emergency Atlus",t:"Unit",f:["Trauma Team","Vehicle","Zetatech"],c:3,p:4,r:1},
{n:"Evelyn Parker — Beautiful Enigma",t:"Legend",f:["Doll"],c:null,p:null,r:2},
{n:"Evelyn Parker — Scheming Siren",t:"Unit",f:["Doll"],c:2,p:0,r:3},
{n:"Field Operator",t:"Unit",f:["Arasaka","Corpo","Techie"],c:3,p:2,r:2},
{n:"Floor It",t:"Program",f:["Merc","Quickhack"],c:1,p:null,r:2},
{n:"Gilded Matón",t:"Unit",f:["Ganger","Valentino"],c:4,p:3,r:2},
{n:"Gorilla Arms",t:"Gear",f:["Cyberware"],c:4,p:3,r:3},
{n:"Goro Takemura — Hands Unclean",t:"Legend",f:["Arasaka","Corpo"],c:5,p:7,r:2},
{n:"Goro Takemura — Losing His Way",t:"Unit",f:["Arasaka","Corpo"],c:4,p:4,r:3},
{n:"Goro Takemura — Vengeful Bodyguard",t:"Legend",f:["Arasaka","Corpo"],c:null,p:null,r:2},
{n:"Hanako Arasaka — Daughter of the Emperor",t:"Legend",f:["Arasaka","Corpo","Netrunner"],c:null,p:null,r:2},
{n:"Hanako Arasaka — In a Gilded Cage",t:"Unit",f:["Arasaka","Corpo","Netrunner"],c:4,p:1,r:2},
{n:"Industrial Assembly",t:"Program",f:["Arasaka","Braindance"],c:1,p:null,r:1},
{n:"Jackie Welles — Mama's Favorite",t:"Legend",f:["Merc"],c:6,p:8,r:2},
{n:"Jackie Welles — Pour One Out For Me",t:"Legend",f:["Merc"],c:null,p:null,r:2},
{n:"Jackie Welles — Ride or Die Choom",t:"Unit",f:["Merc","Valentino"],c:6,p:8,r:2},
{n:"Japantown Jonin",t:"Unit",f:["Tyger Claws"],c:2,p:0,r:2},
{n:"Johnny Silverhand — Rocking Renegade",t:"Legend",f:["Merc","Rocker","Samurai"],c:null,p:null,r:2},
{n:"Kerry Eurodyne — Axe, Attitude, Audience",t:"Legend",f:["Rocker","Samurai"],c:null,p:null,r:2},
{n:"Kerry Eurodyne — The Last Rockerboy",t:"Unit",f:["Rocker","Samurai"],c:4,p:5,r:1},
{n:"Kiroshi Optics",t:"Gear",f:["Cyberware"],c:1,p:1,r:1},
{n:"La Llorona — Ghost of the Past",t:"Unit",f:["Ganger","Valentino"],c:3,p:3,r:1},
{n:"Live with the Aftermath",t:"Program",f:["Plan"],c:3,p:null,r:3},
{n:"Lizzy Wizzy — Delicate Weapon",t:"Unit",f:["Rocker"],c:5,p:2,r:2},
{n:"Lucyna Kushinada",t:"Legend",f:["Overclocking"],c:null,p:0,r:2},
{n:"Maman Brigitte — Spirit of Death",t:"Unit",f:["Mystic","Netrunner","Voodoo Boys"],c:5,p:3,r:4},
{n:"Mandibular Upgrade",t:"Gear",f:["Cyberware"],c:1,p:0,r:2},
{n:"Mantis Blades",t:"Gear",f:["Cyberware"],c:1,p:2,r:1},
{n:"MaxTac Suppression Team",t:"Unit",f:["NCPD"],c:5,p:7,r:1},
{n:"Meredith Stout — Stone Cold Corpo",t:"Unit",f:["Corpo","Militech"],c:4,p:5,r:1},
{n:"Minotaur",t:"Unit",f:["Arasaka","Drone","Militech"],c:7,p:9,r:2},
{n:"Misty Olszewski — Mender of Broken Spirits",t:"Unit",f:["Mystic"],c:3,p:0,r:2},
{n:"Modded Kusanagi",t:"Unit",f:["Tyger Claws","Vehicle"],c:6,p:8,r:2},
{n:"Mox Inciters",t:"Unit",f:["Ganger","Mox"],c:3,p:2,r:2},
{n:"MT0D12 Flathead",t:"Unit",f:["Drone","Militech"],c:5,p:7,r:3},
{n:"Nadia — Fighting Through Grief",t:"Unit",f:["Medtech","Trauma Team"],c:6,p:8,r:2},
{n:"Octant",t:"Unit",f:["Drone","Militech","Zetatech"],c:7,p:8,r:4},
{n:"Offduty Malfini",t:"Unit",f:["Ganger","Voodoo Boys"],c:4,p:5,r:2},
{n:"Over the Edge",t:"Program",f:["Merc"],c:3,p:null,r:2},
{n:"Overwatch — Panam's Gift",t:"Gear",f:["Weapon"],c:4,p:4,r:4},
{n:"Panam Palmer — Nomad Cavalry",t:"Legend",f:["Aldecado","Merc","Nomad"],c:null,p:null,r:2},
{n:"Peace Offering",t:"Program",f:["Braindance"],c:1,p:null,r:1},
{n:"Pepe Najarro — Working Doubles",t:"Unit",f:["Valentino"],c:4,p:6,r:2},
{n:"Placide — Voodoo Sentinel",t:"Unit",f:["Ganger","Netrunner","Voodoo Boys"],c:8,p:10,r:2},
{n:"Psycho Squad",t:"Unit",f:["NCPD"],c:4,p:6,r:1},
{n:"Reboot Optics",t:"Program",f:["Tech"],c:2,p:null,r:2},
{n:"Riding Nomad",t:"Unit",f:["Nomad"],c:5,p:4,r:4},
{n:"River Ward — Detective on the Hunt",t:"Legend",f:["NCPD"],c:null,p:null,r:2},
{n:"Royce — Don't Call Me Simon",t:"Unit",f:["Ganger","Maelstrom"],c:5,p:4,r:2},
{n:"Royce — Psycho on the Edge",t:"Legend",f:["Ganger","Maelstrom"],c:6,p:6,r:2},
{n:"Ruthless Lowlife",t:"Unit",f:["Arasaka","Merc"],c:2,p:1,r:1},
{n:"Saburo Arasaka — Stubborn Patriarch",t:"Legend",f:["Arasaka","Corpo"],c:null,p:0,r:2},
{n:"Sandayu Oda — Hanako's Guardian",t:"Unit",f:["Arasaka","Corpo"],c:7,p:8,r:2},
{n:"Sandevistan",t:"Gear",f:["Cyberware"],c:3,p:2,r:3},
{n:"Satori — Sword of Saburo",t:"Gear",f:["Arasaka","Weapon"],c:2,p:2,r:1},
{n:"Saul Bright — Stormrider",t:"Unit",f:["Aldecado","Nomad"],c:8,p:14,r:2},
{n:"Screw — Lovelorn Fool",t:"Unit",f:["Ganger","Maelstrom"],c:5,p:7,r:2},
{n:"Secondhand Bombus",t:"Unit",f:["Drone","Zetatech"],c:2,p:0,r:2},
{n:"Sketchy Ripper",t:"Unit",f:["Ganger","Ripperdoc","Scavenger"],c:2,p:0,r:2},
{n:"Swordwise Huscle",t:"Unit",f:["Merc"],c:3,p:3,r:2},
{n:"T-Bug — Amateur Philosopher",t:"Unit",f:["Merc","Netrunner"],c:4,p:4,r:2},
{n:"Take Control",t:"Program",f:["Quickhack"],c:2,p:null,r:2},
{n:"The Heist",t:"Program",f:["Merc"],c:2,p:null,r:2},
{n:"The Relic — Experimental Biochip",t:"Gear",f:["Arasaka","Cyberware"],c:5,p:3,r:4},
{n:"V — Corporate Exile",t:"Legend",f:["Corpo","Merc"],c:5,p:8,r:2},
{n:"V — StreetKid",t:"Legend",f:["Merc"],c:5,p:6,r:2},
{n:"Valentino Guerrera",t:"Unit",f:["Ganger","Valentino"],c:3,p:4,r:2},
{n:"Valentino Street Racer",t:"Unit",f:["Valentino","Vehicle"],c:3,p:3,r:2},
{n:"Viktor Vektor — Sit Down and Relax",t:"Legend",f:["Ripperdoc"],c:null,p:null,r:2},
{n:"Viktor Vektor — You Might Feel a Little Pinch",t:"Unit",f:["Ripperdoc"],c:3,p:3,r:2},
{n:"Wraith Marauders",t:"Unit",f:["Ganger","Nomad","Raffen Shiv"],c:5,p:4,r:2},
{n:"Yorinobu Arasaka — Embracing Destruction",t:"Legend",f:["Arasaka","Corpo"],c:null,p:null,r:2},
{n:"Yorinobu Arasaka — Steel Dragon",t:"Unit",f:["Arasaka","Corpo"],c:7,p:9,r:3},
{n:"Zetatech Faceplate",t:"Gear",f:["Cyberware","Zetatech"],c:2,p:2,r:2},
];
